### PR TITLE
Add style guidelines references to README.md

### PR DESCRIPTION
**Pull request by natebower**
Add STYLE_GUIDE.md and TERMS.md cross-references to README.md for top-level visibility.

### Description
_Adds STYLE_GUIDE.md and TERMS.md cross-references to README.md for top-level visibility._

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]
I like it - thanks @natebower

**Review by peternied — COMMENTED** [review]
@natebower Looks like the DCO was missed on this change, could you update the commit? 

More details https://github.com/opensearch-project/.github/pull/129/checks?check_run_id=11098677036

**Comment by Naarcha-AWS** [comment]
@peternied: I went ahead and added DCO sign-off in PR #130. Can you review and merge that PR?

**Comment by natebower** [comment]
Closing in favor of [#130 ](https://github.com/opensearch-project/.github/pull/130)

**Pull request closed without merging**
