### PR TITLE
Add workflow templates for a common pattern.

### PR DESCRIPTION
**Pull request by adnapibar**
### Description
This change adds GitHub Action workflows templates for repositories under the opensearch-project organization. The purpose is to conform to a common pattern for using GitHub Actions for CI & CD.
 
### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/116
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Rabi Panda <pandarab@amazon.com>

### CODE REVIEW

**Comment by dblock** [comment]
Let's add a GH action badge and enable dummy CI on this repo?

**Comment by dblock** [comment]
++ Did you enable this in your fork? Can we see some results?

**Comment by adnapibar** [comment]
> ++ Did you enable this in your fork? Can we see some results?

I ran one on the common-utils fork based on the workflow template https://github.com/adnapibar/common-utils/runs/3234294435?check_suite_focus=true

**Review by dblock — APPROVED** [review]
Nice. 

Maybe the script should be called `dco-signoff-check` just to be super explicit? NBD

**Comment by adnapibar** [comment]
@dblock Thanks! Can you please merge it.

**Comment by dblock** [comment]
Enable GH actions on your fork for the .github repo, and show me that these workflows work? I am pretty sure this will fail if we enable it now because those scripts called `gradlew`.

**Comment by adnapibar** [comment]
> Enable GH actions on your fork for the .github repo, and show me that these workflows work? I think you should do #25 as part of this PR to make sure the workflows are actually function. (I am pretty sure this will fail if we enable it now because those scripts called `gradlew`.)

Added the DCO check workflow for this repo. Here is how it worked in my .github fork https://github.com/adnapibar/.github/runs/3267249808?check_suite_focus=true

Yes, this is not a  Gradle based Java project so for these kind of projects we can remove those steps and only keep the DCO check. For all Gradle based Java project the template can be used as is e.g. here is the workflow on the `common-utils` fork - https://github.com/adnapibar/common-utils/runs/3267308452?check_suite_focus=true

**Comment by dblock** [comment]
I am a little worried about the proliferation of things like `workflow-template`, these are a little hard to discover. Furthermore we have both OpenSearch and OpenSearch Dashboards projects in this repo. What do you think about just merging these into an actually running CI/CD workflow, and either commenting out the parts that invoke scripts or making a comment such as "for example of an OpenSearch workflow, see [link]", "for an example of an OpenSearch Dashboards workflow, see [link]"?

**Pull request closed without merging**
