### PR TITLE
Add DOCS issue template

### PR DESCRIPTION
**Pull request by Naarcha-AWS**
Signed-off-by: Naarcha-AWS <naarcha@amazon.com>

### Description
This PR adds a documentation specific issue template for use in all OpenSearch repositories. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Usually we direct people with documentation issues to documentation repos, e.g. https://github.com/opensearch-project/documentation-website, to open issues. Are you thinking that we will stop doing that and will start opening documentation issues in the same repo as the source code?

**Review by dblock — CHANGES_REQUESTED** [review]
Please match the format of other templates, e.g. https://raw.githubusercontent.com/opensearch-project/.github/main/.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md that is using `###`, has a header, etc.

**Comment by Naarcha-AWS** [comment]
@dblock: Not at this time. I'm adding this template because I can't seem to find a way for the documentation-website repo to be disconnected from the organization templates. Ideally, we would like users making issues on the documentation-website repo to not have to choose between "Feature", "Bug", or "Proposal" templates, and instead have one template consistent for all docs related issues.

**Comment by dblock** [comment]
> @dblock: Not at this time. I'm adding this template because I can't seem to find a way for the documentation-website repo to be disconnected from the organization templates. Ideally, we would like users making issues on the documentation-website repo to not have to choose between "Feature", "Bug", or "Proposal" templates, and instead have one template consistent for all docs related issues.

I see. You should be able to customize this in your repo, see https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository for a bunch of docs. Might require some experimentation.

Since it doesn't look like you want a docs template for all repos in this org, I think we should close this. LMK if otherwise, happy to help in any way I can!

**Pull request closed without merging**
