### PR TITLE
add license header section

### PR DESCRIPTION
**Pull request by wnbts**
Signed-off-by: lai <laijiang@amazon.com>

### Description
This pr adds to the contributing doc the license header with correct copyright info. For more discussion, see https://github.com/opensearch-project/OpenSearch/issues/1056 .

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
Thanks for starting this!

- Let's say "New files in your code contributions should contain the following license header." and "If you are modifying existing files do not remove or modify existing license headers."
- This is a header for Java files, let's make sub-sections with examples for typical stuff like Java, Python, Bash, so that people can copy paste easily. 
- The file has a TOC that needs to be updated.

**Comment by wnbts** [comment]
Thanks for the comments! The pr has been updated. Please let me know if any changes are needed.

**Review by dblock — APPROVED** [review]
LGTM

**Comment by dblock** [comment]
Looks like short versions are preferred, see https://github.com/opensearch-project/.github/pull/29

**Pull request merged**
