### PR TITLE
Update code of conduct email address

### LINKED ISSUE #217: Replace contact information in code-of-conduct, potentially replace the CoC itself.
### What are you proposing?

The OpenSearch Project had adopted the [Amazon Open Source Code of Conduct](https://aws.github.io/code-of-conduct-faq.html) in https://github.com/opensearch-project/.github/blob/main/CODE_OF_CONDUCT.md. The contact information listed at the bottom of that document (`[Contact us](mailto:opensource-codeofconduct@amazon.com).`) needs to change.

### What users have asked for this feature?

Coming from #216.

### What problems are you trying to solve?

Amazon should not be on the hook to enforce CoC in the OpenSearch Software Foundation.

### What is the user experience going to be?

Clear explanation of who to contact for CoC violations.

### LINKED ISSUE #219: [PROPOSAL] Transfer security processes to the OpenSearch Software Foundation
### What are you proposing?

Currently security mailing lists and processes are administered with help from Amazon. For example, in https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#prioritize-security we say "Note that this repository is monitored and supported 24/7 by Amazon Security, see [Reporting a Vulnerability](https://github.com/opensearch-project/.github/blob/main/SECURITY.md) for details." and security @ mailing list is managed by AWS.

1. Transfer all security processes and mailing lists to the OpenSearch Software Foundation.
2. Expand the [security team](https://github.com/opensearch-project/.github/blob/main/SECURITY.md#current-members) to folks from other organizations.

### What users have asked for this feature?

Since https://www.linuxfoundation.org/press/linux-foundation-announces-opensearch-software-foundation-to-foster-open-collaboration-in-search-and-analytics.

### What problems are you trying to solve?

Security should be managed by a trusted and diverse community.

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Update code of conduct email address

### Issues Resolved
- #219
- Closes #217

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — COMMENTED** [review]
Please also update the README.md

**Review by dblock — DISMISSED** [review]
There are a ton of references to this email address in the org. Are we going to leave them to individual repo maintainers?

**Comment by peterzhuamazon** [comment]
> There are a ton of references to this email address in the org. Are we going to leave them to individual repo maintainers?

I think later on we might change to conduct@opensearch.org or similar?
Anyway other repos should refer back to the .github repo files instead of hardcoding it to their own repos.

Thanks.

**Review by peternied — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Thanks @peternied ,

Hi @dblock would you mind give another approval?

Thanks!

**Review by dblock — APPROVED** [review]
Is conduct@opensearch.foundation a real thing? Cool!

**Pull request merged**
